### ISSUE TITLE
Failed to load - server works but can't load some files

### ISSUE THREAD

**Issue by stahlmanDesign** [roman01la/impact-node#1]
Install worked
CD into Impact 1.24 folder
Created entity through command line and it worked.

But when I typed impact-node serve and went to http://localhost:3000/editor , it loads the HTML file but but can't load any scripts or css.

**Comment by roman01la** [comment]
So your run the server inside of actual Impact engine source directory? If so, you shouldn't do it.
Use `impact-node create:project {path to impact dir}` in your project dir, where `{path to impact dir}` is the path to Impact source directory, so it will copy everything from Impact source and setup a new project for you in current directory.

**Comment by stahlmanDesign** [comment]
OK, I see. it works! Thanks for making this.

**Comment by roman01la** [comment]
Glad you've found it useful, thanks!
