### ISSUE TITLE
Build does not include src/ folder in path

### ISSUE THREAD

**Issue by stahlmanDesign** [roman01la/impact-node#3]
I don't know if this is intentional or not, but when you use
`impact-node build`

the path does not look in the src/ folder. This means when I host the game on my server, I have to move the lib/ and media/ folder outside of src/

**Comment by roman01la** [comment]
You are right, `media` dir should be included into build. But `lib` shouldn't, this dir has modules you are using in your code, everything will be included into final `build/game.js`.

**Comment by roman01la** [comment]
Ok, just published v1.2.5, let me know if it works for you.

**Comment by stahlmanDesign** [comment]
OK thanks, it works fine now, with just one more detail: you have to copy an index.html in the build folder that loads game.js

I call mine index-build.html and it's pretty much identical to index.html but loads
`<script type="text/javascript" src="game.js"></script>`

**Comment by roman01la** [comment]
Oh, yes, I should do it as well! 😅

**Comment by roman01la** [comment]
Ok, just released another update. Now you should have `index.html` inside of `build` dir and also `styles.css` with some basic styling.

**Comment by roman01la** [comment]
@stahlmanDesign How's it for you? Let me know.

**Comment by stahlmanDesign** [comment]
Thanks, I'll try it soon.

**Comment by stahlmanDesign** [comment]
All right, it works great, thanks!

**Comment by roman01la** [comment]
Huh, I'm glad this works!
