### ISSUE TITLE
Levels edited with impact-node have bad path to media folder when baked

### ISSUE THREAD

**Issue by stahlmanDesign** [roman01la/impact-node#4]
If I edit a level using impact-node and change the texture of a layer, when I bake, the path is not right.

Should be:
"media/ds_atlas_BTR.png"

But has leading / in path
"/media/ds_atlas_BTR.png"

When I did find and replace to remove the leading slash in the build version file game.js, it works fine.

**Comment by roman01la** [comment]
So the path should be relative to `game.js`?

**Comment by stahlmanDesign** [comment]
I guess so because the media folder and game.js are in the build folder. When in src, when editing, this is different

**Comment by roman01la** [comment]
Ok, I'll look into this. Thanks!

**Comment by stahlmanDesign** [comment]
I have to go, I'll look into this with more detail later. I think /media is saved in level json when editing -- and it needs to be because it works fine, but when baking that link changes

**Comment by stahlmanDesign** [comment]
OK, I noticed that when using impact-node, when I edit a level and choose the texture, it adds a leading slash to the path: /media/mytexture.png  When I use MAMP and the traditional Weltmeister.html setup with PHP, it does not add a leading slash to the media folder: media/mytexture.png   The leading slash does not seem to be a problem when editing, but it causes an error in the build.
![impact-node-editor](https://cloud.githubusercontent.com/assets/972804/7232177/319d6a06-e748-11e4-81a3-13f2f4972bc5.png)
![mamp-weltmeister-editor](https://cloud.githubusercontent.com/assets/972804/7232178/31a9ee2a-e748-11e4-9371-282dc1eacb4b.png)

**Comment by roman01la** [comment]
We should follow original implementation. Thanks for checking this!

**Comment by stahlmanDesign** [comment]
I think you could fix this by putting the index.html and weltmeister.html files into src/ along with lib/ and media/ -- that's how the original implementation was.

Then when you do a build, the same relative path will be respected.

If you make this change you would need to change impact-node from pointing to src/ and instead point to the same root folder as index.html, because the files will all be inside src/ (and after a build, build/)

**Comment by roman01la** [comment]
Looks like this may not take much effort to do. I'm on it.

**Comment by roman01la** [comment]
Ok, I just fixed assets path (removed leading slash), so everything should be ok for now. Just a few more changes and I'll publish an update.

**Comment by roman01la** [comment]
Done! Also, watch mode turned out to be broken. I've added a [changelog](https://github.com/roman01la/impact-node/blob/master/CHANGELOG.md) to keep track of everything.

**Comment by roman01la** [comment]
Let me know if you'd like to have some particular features within the tool 🔨

**Comment by stahlmanDesign** [comment]
I had to fix my levels that I made with previous versions of impact-node, but now that I re-selected the texture, the leading slash is gone, so that is good.

And I just confirmed that it builds correctly. Thanks!

**Comment by roman01la** [comment]
Nice!
