### ISSUE TITLE
JSON Parse Error

### ISSUE THREAD

**Issue by ghost** [roman01la/impact-node#7]
I have not had an issue previously but now since upgrading to el cap on my macbook air I have got this issue appearing in console.log when going to localhost:3000/editor

Failed to load entity list via glob.php: SyntaxError: JSON Parse error: Unrecognized token '<'

and then it just spits out the php file

I know it talks about circular entities, however I have checked and there is no dependancies, the issue started after upgrading.

Thanks,

Ben

**Comment by stahlmanDesign** [comment]
Why are you using php with impact-node? I don't know if that's the problem, but I think you should either use php or node, not both together.

**Comment by ghost** [comment]
I am not using php, but for some reason it is printing the contents of the php file in the error message. Please see attached screenshots.

Regarding the error around circular entities, I have double checked all the entity files and I cannot see a conflict, but that is the second in the list of errors.

Thanks for your help

![screen shot 2016-03-14 at 11 04 58](https://cloud.githubusercontent.com/assets/180467/13732336/c3094a48-e9d4-11e5-86c8-57fedf3677b7.png)
![screen shot 2016-03-14 at 11 05 12](https://cloud.githubusercontent.com/assets/180467/13732337/c3c18586-e9d4-11e5-86b1-ee54422543ed.png)

**Comment by roman01la** [comment]
@jakkblakk Seems like you are getting a php file as a response to http request. I'm not getting this error on El Capitan. The error tells that a file `glob.php` is being used to request data, it means that PHP is involved here. This should be handled by Node.js. Did you update Impact files in your project manually?

**Comment by roman01la** [comment]
Closing this for now due to absence of activity. Please reopen if you encounter the issue again.
